name: gb-probabilistic-epf
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy=2.3.3
  - pandas=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - pyarrow=23.0.0
  - pip:
      - tensorflow==2.21.0
      - keras==3.15.0
      - quantile-forest==1.4.1
